### ISSUE TITLE
GraphiQL "subscriptionsClient.subscribe is not a function"

### ISSUE THREAD

**Issue by RusticFlare** [graphql-java-kickstart/graphql-spring-boot#220]
## The Bug 

When I try to subscribe through GraphiQL I see this error:

![Screen Shot 2019-03-26 at 11 13 25](https://user-images.githubusercontent.com/5823777/54993117-056bb680-4fb9-11e9-8385-1b1a8eb13a80.png)

## My Setup

I have a schema

```graphql
type Query {
    hello : String!
}

type Subscription {
    helloWorld : String!
}
```

and resolvers (in Kotlin)

```kotlin
import com.coxautodev.graphql.tools.GraphQLQueryResolver
import com.coxautodev.graphql.tools.GraphQLSubscriptionResolver
import org.reactivestreams.Publisher
import org.springframework.stereotype.Component
import reactor.core.publisher.Flux

@Component
class Query : GraphQLQueryResolver {
    fun hello() = "Hello World!"
}

@Component
class Subscription : GraphQLSubscriptionResolver {
    fun helloWorld(): Publisher<String> = Flux.just("Hello", "World!")
}
```

and dependencies in `build.gradle`

```groovy
dependencies {
    compile 'com.graphql-java-kickstart:graphql-spring-boot-starter:5.7.0'
    runtime 'com.graphql-java-kickstart:graphiql-spring-boot-starter:5.7.0'
}
```

### Queries Work

![Screen Shot 2019-03-26 at 11 23 59](https://user-images.githubusercontent.com/5823777/54993570-03562780-4fba-11e9-8566-9bb27e99f8de.png)

### Subscriptions Work With Version `5.6.0`

The last versions for subscriptions to work with GraphiQL seems to be `5.6.0`:

```groovy
dependencies {
    compile 'com.graphql-java-kickstart:graphql-spring-boot-starter:5.6.0'
    runtime 'com.graphql-java-kickstart:graphiql-spring-boot-starter:5.6.0'
}
```

**Comment by oliemansm** [comment]
Thanks for the report. It has to do with breaking changes in `subscriptions-transport-ws`, see also: https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/issues/13. Until a fix is found and implemented either downgrade the GraphiQL version to use, or use Altair instead which does not have this problem.

**Comment by Selectorrr** [comment]
Any updates? We are stuck on graphiql version 0.11.11 but current is 0.13.0. As I understand the problem in the subscriptions-transport-ws library, can we freeze the version of this library instead of the graphiql?

**Comment by oliemansm** [comment]
The current version used is 0.13.0 along with 0.9.15 of subscription-transport-ws and I'm not seeing those errors anymore. So, it has been solved so it seems.

**Comment by krishofmans** [comment]
I was on 5.10.0 and still got the error, setting it back to 5.6.0 only for graphiql is our current workaround.

**Comment by Selectorrr** [comment]
The error still exists, it is necessary to reopen issue

**Comment by krishofmans** [comment]
I've retried this using 6.0.0 but I'm still having the same issue, If you want to have a look I can share the project's gitlab link.

You can test it here: https://poker.otd.rotate-it.be/graphiql
The code is also available: https://gitlab.rotate-it.be/tripled/poker

**Comment by mkaraula** [comment]
Can confirm. We are experiencing the same Issue on `6.0.1`

**Comment by oliemansm** [comment]
I just tested this again with version 7.0.0 of this spring boot starter, and I'm not getting any errors. I ran it both from the [example](https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/example) application in this library, and in one of my own projects. They used to fail before, but both run fine for me at this time. 

I also see the websocket with subscriptions is started successfully including the keep alive messages.

I tried both with the embedded graphiql version, as well as with version 0.17.5 by setting the configuration:
```
graphiql.cdn.enabled=true
graphiql.cdn.version=0.17.5
```

Can you guys check if it's working for you now too? And otherwise there must be something in the configuration that's different that's causing it.

**Comment by krishofmans** [comment]
Hi @oliemansm 

I performed the upgrades last night, and it's running live on:
https://pokers.otd.rotate-it.be/graphiql
It's behind a keycloak gatekeeper now, the login is: test/test

It is using 0.17.5, provided by the CDN:
<img width="2279" alt="Screenshot 2020-03-24 at 08 39 21" src="https://user-images.githubusercontent.com/999774/77400092-f75a9c80-6daa-11ea-882a-b0616218ff6e.png">

The gradle file looks like this:
https://gitlab.rotate-it.be/tripled/poker/-/blob/master/build.gradle

With the relevant part looking like: 
```
		implementation 'com.graphql-java-kickstart:graphql-spring-boot-starter:7.0.0'
		implementation 'com.graphql-java-kickstart:graphiql-spring-boot-starter:7.0.0'
		implementation 'com.graphql-java-kickstart:altair-spring-boot-starter:7.0.0'
		implementation 'com.graphql-java-kickstart:voyager-spring-boot-starter:7.0.0'
		implementation 'com.expediagroup:graphql-kotlin-schema-generator:2.0.0-RC12.1'
```

The configuration is very minimal, and mostly resolved around generating the schema from code
```kotlin
import com.expediagroup.graphql.SchemaGeneratorConfig
import com.expediagroup.graphql.TopLevelObject
import com.expediagroup.graphql.toSchema
import graphql.schema.GraphQLSchema
import graphql.schema.idl.SchemaPrinter
import org.slf4j.LoggerFactory
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.web.socket.config.annotation.EnableWebSocket

@Configuration
@EnableWebSocket
class CustomGraphqlConfiguration {
    private val logger = LoggerFactory.getLogger(CustomGraphqlConfiguration::class.java)

    @Bean
    fun schemaConfig(): SchemaGeneratorConfig = SchemaGeneratorConfig(
            supportedPackages = listOf(
                    "io.tripled.poker.graphql.query",
                    "io.tripled.poker.graphql.mutation",
                    "io.tripled.poker.graphql.subscription",
                    "io.tripled.poker.vocabulary",
                    "io.tripled.poker.app.api.response"
            )
    )

    @Bean
    fun schema(
            queries: List<Query>,
            mutations: List<Mutation>,
            subscriptions: List<Subscription>,
            schemaConfig: SchemaGeneratorConfig
    ): GraphQLSchema {
        fun List<Any>.toTopLevelObjectDefs() = this.map {
            TopLevelObject(it)
        }

        val schema = toSchema(
                queries = queries.toTopLevelObjectDefs(),
                mutations = mutations.toTopLevelObjectDefs(),
                subscriptions = subscriptions.toTopLevelObjectDefs(),
                config = schemaConfig
        )
        logger.info(SchemaPrinter(
                SchemaPrinter.Options.defaultOptions()
                        .includeScalarTypes(true)
                        .includeExtendedScalarTypes(true)
                        .includeSchemaDefinition(true)
        ).print(schema)
        )
        return schema
    }
}
```

So I still have the issue, but I will compare this to your example project again, and see if I can spot the difference.

Thanks

**Comment by krishofmans** [comment]
Hello @oliemansm 

Just checked out master, ran the example, and it does this in both chrome and safari:
<img width="1870" alt="Screenshot 2020-03-24 at 14 31 37" src="https://user-images.githubusercontent.com/999774/77430890-2ccbae00-6ddc-11ea-8fb4-f6062b5ff65e.png">

I will ask someone else to verify this (so that this is not my laptop), but it looks like the exact same error in your example, and in our own application.

**Comment by krishofmans** [comment]
Hello @oliemansm 

Had 3 other devs spin up your subscription example, they all get the same error.

**Comment by stevelaclasse** [comment]
i am facing the same issue with graphql-java. do i have to use another URL for the web socket (for the subcription, if yes how to configure it), because actually i still use /graphql

**Comment by oliemansm** [comment]
@krishofmans This is crazy. I just logged into your test setup with Chrome and it's working fine for me. The only thing coming to mind that might explain this is that I'm running on Linux (Fedora).

![image](https://user-images.githubusercontent.com/13518144/78161128-48baf980-7445-11ea-9939-3dadf5ba5792.png)

Just tested it in Firefox on Linux too and see the subscription setup correctly and see messages being sent.

The fact that I'm not able to reproduce it locally makes it really hard to fix, but I'll dive into it again.

**Comment by oliemansm** [comment]
Nevermind, I'm being stupid :joy:

**Comment by oliemansm** [comment]
Fixing the version of the transport as suggested by @Selectorrr did the trick. In the future any contributions as PRs for fixes like these are highly appreciated, since my time is very limited. So any help in fixing issues will benefit everybody depending on these libraries.

This fix will be part of 7.0.2. You can try it out by using 7.0.2-SNAPSHOT version if you want. To be able to do that you have to add the jfrog snapshot repository located at https://oss.jfrog.org/artifactory/oss-snapshot-local.

**Comment by krishofmans** [comment]
Thanks @oliemansm, I appreciate all the work you have done on graphql-java-kickstart in that limited time.

I've tried the 7.0.2-SNAPSHOT, initially I got a different error:
`"Your subscription data will appear here after server publication!"`

Serverside stacktrace:
```
graphql.execution.UnknownOperationException: Must provide operation name if query contains multiple operations.
	at graphql.language.NodeUtil.getOperation(NodeUtil.java:75) ~[graphql-java-14.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:64) ~[graphql-java-14.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:623) ~[graphql-java-14.0.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556) ~[graphql-java-14.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:520) ~[graphql-java-14.0.jar:na]
	at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:26) ~[graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.execution.subscriptions.apollo.SubscriptionStartCommand.executeAsync(SubscriptionStartCommand.java:40) ~[graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.execution.subscriptions.apollo.SubscriptionStartCommand.apply(SubscriptionStartCommand.java:31) ~[graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:24) ~[graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:11) ~[graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:127) [graphql-java-servlet-9.1.0.jar:na]
	at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:123) [graphql-java-servlet-9.1.0.jar:na]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-embed-websocket-9.0.33.jar:9.0.33]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.33.jar:9.0.33]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

Removing all other queries/mutations from graphql solved that and the subscription is working!

So indeed this seems to be fixed.

**Comment by ChristianIvicevic** [comment]
I am having this issue with GraphiQL 0.17.5 and 7.0.1 of this library supplied from the CDN right now.

**Comment by oliemansm** [comment]
This issue is linked to milestone 7.1.0 so indeed not fixed in 7.0.1.

**Comment by Kassan424kh** [comment]
> This issue is linked to milestone 7.1.0 so indeed not fixed in 7.0.1.

7.1.0 works fine
