### ISSUE TITLE
CORS functionality cannot be disabled with property 'graphql.servlet.cors-enabled'

### ISSUE THREAD

**Issue by bvklingeren** [graphql-java-kickstart/graphql-spring-boot#763]
**Describe the bug**

The GraphQLWebAutoConfiguration class contains a 'corsConfigurer' bean factory method which has a @ConditionalOnProperty annotation with the value of 'graphql.servlet.corsEnabled'. This does not match with the 'graphql.servlet.cors-enabled' config parameter which is the expected format of such a property and therefore it doesn't prevent the CorsFilter to be created when you define the 'graphql.servlet.cors-enabled' config parameter with the value 'false'.

**To Reproduce**
1. Register config param 'graphql.servlet.cors-enabled' in e.g. application.properties with value 'false'
2. Create a breakpoint at line 127 of GraphQLWebAutoConfiguration
3. Start your SB app in debug mode
4. The debugger stops at the breakpoint

**Expected behavior**
The breakpoint should not have been reached and therefore the CorsFilter should not have been created.

**Screenshots**
N/a

**Desktop (please complete the following information):**
N/a

**Additional context**
N/a

**Comment by BlasiusSecundus** [comment]
This seems to be a duplicate of https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/682, which was already resolved (although the fix is not yet in the latest release, only in snapshot version).

**Comment by bvklingeren** [comment]
Ah yes, you're right. I'll be looking out for the new release then.

**Comment by kumaritian** [comment]
The issue still exists in the spring-boot 2.7.2 version.

**Comment by oliemansm** [comment]
@kumaritian I've just tested this using the reproduction script of the original reporter with v13.0.0 icw Spring Boot and can confirm it is actually solved. So you must be doing something differently or are experiencing some other kind of issue.

**Comment by kumaritian** [comment]
@oliemansm  : In which Spring boot version the issue got resolved. Currently I am using 2.7.1 version.

**Comment by oliemansm** [comment]
@kumaritian It's not a specific Spring Boot version. It's resolved in graphql-spring-boot, so you need to upgrade that to v13.0.0

**Comment by kumaritian** [comment]
@oliemansm : After updating to V13.0.0 from V12.0.0 I am getting below on application start up.
               <dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>13.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-java-tools</artifactId>
			<version>13.0.0</version>
		</dependency>

**Error**
java.lang.IllegalStateException: Failed to introspect Class [graphql.kickstart.autoconfigure.editor.graphiql.GraphiQLAutoConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@22d8cfe0]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485) ~[spring-core-5.3.22.jar:5.3.22]
	.....
	....
	....
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
	at com.mt.amp.pot.service.aggregator.ServiceAggregatorApplication.main(ServiceAggregatorApplication.java:22) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/reactive/function/server/RouterFunction
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.22.jar:5.3.22]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.web.reactive.function.server.RouterFunction
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 25 common frames omitted

**Comment by oliemansm** [comment]
This should be a separate discussion in Q&A instead of hijacking this issue for this problem. It's not related. Remove the `graphql-java-tools` dependency. `graphql-spring-boot-starter` pulls in the correct version.

**Comment by kumaritian** [comment]
@oliemansm : Thanks for the input and I did removed `graphql-java-tools` and tried it but still the same error :(

**Comment by oliemansm** [comment]
Open a separate discussion for this to get further assistance.

**Comment by kumaritian** [comment]
@oliemansm : Thanks for your support. FYI : I have created a new issue https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/856
